import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const replicaSans = localFont({
  src: [
    {
      path: "./fonts/Replica-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Replica-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Replica-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-replica-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${replicaSans.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
